version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - .:/app              # monta tu proyecto en el contenedor
      - /app/node_modules   # evita conflictos entre dependencias host/cont
    environment:
      - PORT=5000
      - MOCK_API=http://simulado:80
    depends_on:
      - simulado

  simulado:
    image: ldabiralai/simulado:latest
    ports:
      - "3001:80"
    volumes:
      - ./shared/simulado:/app
    command: ./bin/simulado -f /app/mocks.json
